"""initial_schema

Revision ID: 162294e77741
Revises: 
Create Date: 2026-04-15 01:43:48.074832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '162294e77741'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Ordered array of author names, e.g. ["Singh A", "Patel R"]'),
    sa.Column('journal', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('volume', sa.String(length=64), nullable=True),
    sa.Column('issue', sa.String(length=64), nullable=True),
    sa.Column('pages', sa.String(length=64), nullable=True),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('pmid', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('full_text_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('PUBMED', 'SCHOLAR', 'IDSP', 'MOHFW', name='article_source'), nullable=False),
    sa.Column('disease_category', sa.String(length=256), nullable=True),
    sa.Column('study_type', sa.String(length=128), nullable=True, comment='e.g. RCT, cohort, case-control, systematic-review, surveillance-report'),
    sa.Column('geography', sa.String(length=256), nullable=True, comment='Country / region the study covers'),
    sa.Column('keywords', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Array of keyword strings, e.g. ["dengue", "vector control"]'),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True, comment='When the article was pushed to the Elasticsearch index'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_disease_category'), 'articles', ['disease_category'], unique=False)
    op.create_index(op.f('ix_articles_doi'), 'articles', ['doi'], unique=True)
    op.create_index(op.f('ix_articles_pmid'), 'articles', ['pmid'], unique=True)
    op.create_index(op.f('ix_articles_source'), 'articles', ['source'], unique=False)
    op.create_index('ix_articles_source_year', 'articles', ['source', 'year'], unique=False)
    op.create_index(op.f('ix_articles_year'), 'articles', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('institution', sa.String(length=512), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('RESEARCHER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=True, comment='SHA-256 hex digest of the current refresh token'),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_refresh_token_hash'), 'users', ['refresh_token_hash'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Full TipTap/ProseMirror document JSON'),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', name='paper_status'), nullable=False),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=True)
    op.create_index(op.f('ix_papers_status'), 'papers', ['status'], unique=False)
    op.create_index(op.f('ix_papers_user_id'), 'papers', ['user_id'], unique=False)
    op.create_table('reading_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='NULL until the session is closed or the tab is unloaded'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Computed from ended_at - started_at; may be set client-side'),
    sa.Column('scroll_depth', sa.Float(), nullable=True, comment='0.0 – 1.0 fraction of article body scrolled'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Inline annotation or highlight captured during this session'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_sessions_article_id'), 'reading_sessions', ['article_id'], unique=False)
    op.create_index('ix_reading_sessions_started_at', 'reading_sessions', ['started_at'], unique=False)
    op.create_index('ix_reading_sessions_user_id', 'reading_sessions', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Active filter state, e.g. {"source": "pubmed", "year_min": 2018, "study_type": "RCT"}'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='Search target, e.g. pubmed, scholar, idsp, all'),
    sa.Column('result_count', sa.Integer(), nullable=True, comment='Number of results returned for this query'),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_history_searched_at', 'search_history', ['searched_at'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True, comment='Hex color code, e.g. #FF5733'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_index('ix_tags_user_id', 'tags', ['user_id'], unique=False)
    op.create_table('user_library',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Array of user-defined tag strings, e.g. ["to-read", "dengue"]'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'article_id')
    )
    op.create_index('ix_user_library_user_id', 'user_library', ['user_id'], unique=False)
    op.create_table('collection_papers',
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment='Display order within the collection'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'article_id')
    )
    op.create_index('ix_collection_papers_article_id', 'collection_papers', ['article_id'], unique=False)
    op.create_index('ix_collection_papers_collection_id', 'collection_papers', ['collection_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False, comment='Server-side path or object-storage key'),
    sa.Column('columns', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Array of column descriptor objects, e.g. [{"name": "age", "dtype": "int64"}]'),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_paper_id'), 'datasets', ['paper_id'], unique=False)
    op.create_index(op.f('ix_datasets_user_id'), 'datasets', ['user_id'], unique=False)
    op.create_table('paper_tags',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.create_index('ix_paper_tags_article_id', 'paper_tags', ['article_id'], unique=False)
    op.create_index('ix_paper_tags_tag_id', 'paper_tags', ['tag_id'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('citation_style', sa.String(length=64), nullable=True, comment='e.g. APA, Vancouver, Harvard'),
    sa.Column('citation_text', sa.Text(), nullable=True, comment='Pre-formatted citation string for the chosen style'),
    sa.Column('position', sa.Integer(), nullable=False, comment="Order of this citation in the paper's reference list"),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'article_id', name='uq_reference_paper_article')
    )
    op.create_index(op.f('ix_references_article_id'), 'references', ['article_id'], unique=False)
    op.create_index(op.f('ix_references_paper_id'), 'references', ['paper_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('analysis_type', sa.String(length=128), nullable=False, comment='e.g. descriptive_stats, chi_square, kaplan_meier, linear_regression'),
    sa.Column('parameters', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Input parameters passed to the analysis function'),
    sa.Column('results', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Structured output: test statistics, p-values, coefficients, etc.'),
    sa.Column('chart_data', postgresql.JSONB(astext_type=Text()), nullable=True, comment='Vega-Lite / Chart.js spec or raw series data for rendering'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_dataset_id'), 'analysis_results', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_dataset_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_references_paper_id'), table_name='references')
    op.drop_index(op.f('ix_references_article_id'), table_name='references')
    op.drop_table('references')
    op.drop_index('ix_paper_tags_tag_id', table_name='paper_tags')
    op.drop_index('ix_paper_tags_article_id', table_name='paper_tags')
    op.drop_table('paper_tags')
    op.drop_index(op.f('ix_datasets_user_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_paper_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('ix_collection_papers_collection_id', table_name='collection_papers')
    op.drop_index('ix_collection_papers_article_id', table_name='collection_papers')
    op.drop_table('collection_papers')
    op.drop_index('ix_user_library_user_id', table_name='user_library')
    op.drop_table('user_library')
    op.drop_index('ix_tags_user_id', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index('ix_search_history_searched_at', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index('ix_reading_sessions_user_id', table_name='reading_sessions')
    op.drop_index('ix_reading_sessions_started_at', table_name='reading_sessions')
    op.drop_index(op.f('ix_reading_sessions_article_id'), table_name='reading_sessions')
    op.drop_table('reading_sessions')
    op.drop_index(op.f('ix_papers_user_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_users_refresh_token_hash'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_articles_year'), table_name='articles')
    op.drop_index('ix_articles_source_year', table_name='articles')
    op.drop_index(op.f('ix_articles_source'), table_name='articles')
    op.drop_index(op.f('ix_articles_pmid'), table_name='articles')
    op.drop_index(op.f('ix_articles_doi'), table_name='articles')
    op.drop_index(op.f('ix_articles_disease_category'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
